name: Build extension

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install
    - run: npm run sign
      env:
        CI: true
        WEB_EXT_API_KEY: ${{ secrets.JWT_ISSUER }}
        WEB_EXT_API_SECRET: ${{ secrets.JWT_SECRET }}
    - uses: actions/upload-artifact@v1
      with:
        name: linkedin-mieux
        path: build/
